prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "otel-collector"
        scrape_interval: 15s
        static_configs:
          - targets:
              [
                "otel-collector-opentelemetry-collector.otel-collector.svc.cluster.local:8889",
              ]
grafana:
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Admin

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: "Custom"
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          options:
            path: /var/lib/grafana/dashboards

  extraConfigmapMounts:
    - name: grafana-dashboards
      mountPath: /var/lib/grafana/dashboards
      configMap: grafana-dashboards
      readOnly: true

  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-gateway.loki.svc.cluster.local/
      access: proxy
      isDefault: false
      orgId: 1
    - name: Tempo
      type: tempo
      access: proxy
      orgId: 1
      url: http://tempo-gateway.tempo.svc.cluster.local/
      basicAuth: false
      isDefault: false
      version: 1
      editable: false
      apiVersion: 1
      uid: tempo
    - name: Pyroscope
      type: grafana-pyroscope-datasource
      url: http://pyroscope.pyroscope.svc.cluster.local:4040
      access: proxy
      isDefault: false
      orgId: 1
