service:
  type: ClusterIP
  port: 4040

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  size: 5Gi

config:
  log-level: debug
  scrape-configs:
    enabled: false
