global:
  clusterDomain: "cluster.local"
gateway:
  enabled: true
minio:
  enabled: true

storage:
  trace:
    backend: s3
    s3:
      access_key: "grafana-tempo"
      secret_key: "supersecret"
      bucket: "tempo-traces"
      endpoint: "tempo-minio:9000"
      insecure: true
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false

distributor:
  config:
    log_received_spans:
      enabled: true
    log_discarded_spans:
      enabled: true
# https://github.com/grafana/tempo/issues/4299 - distibuted tempo do not have by default TraceQL enabled
metricsGenerator:
  enabled: true
