mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib

config:
  receivers:
    jaeger: null
    zipkin: null
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch:
      send_batch_size: 8192
      timeout: 5s
    memory_limiter:
      check_interval: 5s
      limit_mib: 800
      spike_limit_mib: 150

  exporters:
    debug:
      verbosity: detailed
    otlphttp/logs:
      endpoint: http://loki-gateway.loki.svc.cluster.local/otlp
      tls:
        insecure: true
    prometheusremotewrite:
      endpoint: prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090/api/v1/write

  service:
    extensions:
      - health_check
    pipelines:
      traces:
        receivers:
          - otlp
        exporters:
          - debug
      metrics:
        receivers:
          - otlp
        exporters:
          - debug
          - prometheusremotewrite
      logs:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - batch
        exporters:
          - otlphttp/logs

ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP
  otlp-grpc:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    protocol: TCP
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    protocol: TCP

ingress:
  enabled: false

serviceMonitor:
  enabled: true
  extraLabels:
    release: kube-prometheus-stack
