scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 5s
    static_configs:
      - targets: ["0.0.0.0:8888"]
      - targets: ["0.0.0.0:8889"]
grafana:
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Admin

  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-gateway.loki.svc.cluster.local/
      access: proxy
      isDefault: false
      orgId: 1
