replicaCount: 1

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: "serviceaccount"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

orderService:
  image:
    repository: order-service
    pullPolicy: Always
    tag: "0.1.0"
  service:
    type: ClusterIP
    port: 50052
    metricPort: 8050
  resources: {}

inventoryService:
  image:
    repository: inventory-service
    pullPolicy: Always
    tag: "0.1.0"
  service:
    type: ClusterIP
    port: 50051
    metricPort: 8050
  resources: {}

otel:
  collector:
    endpoint: "otel-collector.observability.svc.cluster.local:4317"

prometheus:
  enabled: true
  metricsPath: "/metrics"
