replicaCount: 1

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: "serviceaccount"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

orderService:
  image:
    repository: order-service
    pullPolicy: Always
    tag: "0.1.0"
  service:
    type: ClusterIP
    port: 50052
    metricPort: 8050
  resources: {}

inventoryService:
  image:
    repository: inventory-service
    pullPolicy: Always
    tag: "0.1.0"
  service:
    type: ClusterIP
    port: 50051
    metricPort: 8050
  resources: {}

otel:
  collector:
    endpoint: "otel-collector.observability.svc.cluster.local:4317"

prometheus:
  enabled: true
  metricsPath: "/metrics"

opentelemetry-collector:
  enabled: true
  mode: deployment
  image:
    repository: otel/opentelemetry-collector-k8s
  config:
    exporters:
      debug: {}
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
