replicaCount: 1

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: "serviceaccount"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

orderService:
  image:
    repository: order-service
    pullPolicy: Always
    tag: "0.1.0"
  service:
    type: ClusterIP
    port: 50052
  resources: {}

inventoryService:
  image:
    repository: inventory-service
    pullPolicy: Always
    tag: "0.1.0"
  service:
    type: ClusterIP
    port: 50051
  resources: {}

otel:
  collector:
    endpoint: "demo-opentelemetry-collector:4317"

opentelemetry-collector:
  enabled: true
  mode: deployment
  image:
    repository: otel/opentelemetry-collector-contrib
  fullnameOverride: "otel-collector"

  presets:
    kubernetesAttributes:
      enabled: true
      extractAllPodLabels: true
      extractAllPodAnnotations: true
    kubeletMetrics:
      enabled: false
    clusterMetrics:
      enabled: true

  config:
    receivers:
      jaeger: null
      zipkin: null

    exporters:
      debug:
        verbosity: detailed

      prometheus:
        endpoint: ${env:MY_POD_IP}:8889

    service:
      pipelines:
        traces: null

        metrics:
          receivers:
            - otlp
            - prometheus
          processors:
            - memory_limiter
            - batch
          exporters:
            - debug
            - prometheus

        logs: null

  ports:
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false
    metrics:
      enabled: true
      containerPort: 8889
      servicePort: 8889
      protocol: TCP

  ingress:
    enabled: false

  serviceMonitor:
    enabled: true

    extraLabels:
      release: prometheus

kube-prometheus-stack:
  grafana:
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Admin
