replicaCount: 1

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: "serviceaccount"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

orderService:
  image:
    repository: order-service
    pullPolicy: Always
    tag: "0.1.0"
  service:
    type: ClusterIP
    port: 50052
  resources: {}

inventoryService:
  image:
    repository: inventory-service
    pullPolicy: Always
    tag: "0.1.0"
  service:
    type: ClusterIP
    port: 50051
  resources: {}

otel:
  collector:
    endpoint: "{{ .Release.Name }}-opentelemetry-collector:4317"

opentelemetry-collector:
  enabled: true
  mode: deployment
  image:
    repository: otel/opentelemetry-collector-contrib # Changed from otel/opentelemetry-collector-k8s
  config:
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      debug: {}
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug] # Traces still go to debug exporter
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheus] # Metrics now go to prometheus exporter
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug] # Logs still go to debug exporter

prometheus:
  enabled: true
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: "prometheus"
          static_configs:
            - targets: ["localhost:9090"]

        - job_name: "opentelemetry-collector"
          scrape_interval: 15s
          static_configs:
            - targets:
                [
                  '{{ printf "%s-opentelemetry-collector:%d" .Release.Name 8889 }}',
                ]
