apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "grpc-load-generator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
        - name: ghz
          image: ghcr.io/bojand/ghz
          args:
            - "--proto"
            - "{{ .Values.grpc.proto }}"
            - "--call"
            - "{{ .Values.grpc.call }}"
            - "--rps"
            - "{{ .Values.grpc.rps }}"
            - "-d"
            - {{ .Values.grpc.payload | quote }}
            - "--insecure"
            - "-c"
            - "{{ .Values.grpc.concurrency }}"
            - "-n"
            - "{{ .Values.grpc.requests }}"
            - "{{ .Values.grpc.target }}"
          volumeMounts:
            - name: proto-volume
              mountPath: /proto
      volumes:
        - name: proto-volume
          configMap:
            name: order-proto
      restartPolicy: Never
  backoffLimit: 2
