{
 "title": "Inventory",
 "time": { "from": "now-10m", "to": "now" },
 "panels": [
  {
   "title": "InventoryRequestsTotal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "inventory_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "InventoryRequestLatencyMsBucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "inventory_request_latency_ms_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InventoryRequestLatencyMsCount",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "inventory_request_latency_ms_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InventoryRequestLatencyMsSum",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "inventory_request_latency_ms_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InventoryServiceLogs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"inventory-service\"} |= ``"
    }
   ]
  }
 ]
}