{
 "title": "Order",
 "time": { "from": "now-10m", "to": "now" },
 "panels": [
  {
   "title": "OrderRequestLatencyMsSum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "order_request_latency_ms_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OrderRequestLatencyMsCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "order_request_latency_ms_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OrderRequestLatencyMsBucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "order_request_latency_ms_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OrderRequestsTotal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "order_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}