apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-order-service
  labels:
    {{- include "microservice-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
spec:
  type: {{ .Values.orderService.service.type }}
  ports:
    - port: {{ .Values.orderService.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "microservice-demo.orderService.selectorLabels" . | nindent 4 }}
